---
name: myappworkflow
on:
  workflow_dispatch:
    inputs:
      myinput:
        type: choice
        options:
          - Dev
          - Stage
          - Prod
env:
  AWS_ACCESSKEY: 'ABCDEFG'
  AWS_SECRET: '123456'
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      Build_Env: 'Build Env'
      Build_SECRET: 'Build Secret'
    steps:
      - name: Sample Command
        env:
          Steps_evn_Env: 'Steps Env'
          Steps_SECRET: 'Steps Secret'
        run: |
          echo "Hello World"
          echo ${{env.Steps_evn_Env}}
      - name: Context
        run: echo ${{runner.os}} && echo ${{github.actor}}












