---
name: myappworkflow
on:
  workflow_dispatch:
    inputs:
      myinput:
        type: choice
        options:
          - Dev
          - Stage
          - Prod
env:
  AWS_ACCESSKEY: 'ABCDEFG'
  AWS_SECRET: '123456'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sample Command
        run: echo "Hello World"
      - name: Context
        run: echo ${{runner.os}} && echo ${{github.actor}}







