---
name: myappworkflow
on:
  workflow_dispatch:
    inputs:
      myinput:
        type: choice
        options:
          - Dev
          - Stage
          - Prod
jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - name: Sample Command
        run: echo "Hello World"



